default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: 
    <<: *default
    host: localhost
    database: tidder_development

test:
    <<: *default
    host: localhost
    database: tidder_test

production:
    <<: *default
    database: tidder_production
    username: tidder
    password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>